### ISSUE TITLE
[FEATURE] More capabilities setting an image

### ISSUE THREAD

**Issue by DaRobsi** [0xk1f0/rwpspread#104]
I'd really love to see two capabilities for this wonderful tool, namely:
- the possibility to set a folder with images, rwpspread then randomly taking one out of it
- the possibility to set different images for different times (i.e. one for day, one for night)

thanks in advance!

**Comment by 0xk1f0** [comment]
Random selection from folder done in: https://github.com/0xk1f0/rwpspread/commit/66f8f8f56504920f270a01f5dc7cb40ab32645db

**Comment by 0xk1f0** [comment]
I think timers are out of scope for this tool for now. It can surely be done with [systemd-timers](https://wiki.archlinux.org/title/Systemd/Timers) or [cronjobs](https://wiki.archlinux.org/title/Cron).

Feel free to open another issue if I decide to implement an `ipc` someday, I think using a `ctl` tool that can set off commands to the daemon would be a better implementation.
