### ISSUE TITLE
Use `rwpspread` to only generate images

### ISSUE THREAD

**Issue by apprehensions** [0xk1f0/rwpspread#98]
Hi, i would like to use `rwpspread` to only generate images for my monitor layout, so i can use a wallpaper setter externally.

**Comment by 0xk1f0** [comment]
Using

```bash
rwpspread -i <path/to/image>
```

Should only generate the images for the layout, without doing anything else. It will save the images to the current working directory.

Does this fit your use-case?

**Comment by 0xk1f0** [comment]
https://github.com/0xk1f0/rwpspread/commit/b766da55c3e695ee414889524eae64cdc3f5f0c4 makes the `-d` daemon mode non-dependent on a backend, which I forgot to do before releasing `0.2.0`. I will draft a new release for this soon, probably.

This should allow using an independent backend while still having the benefit of automatic resplits on output changes.

**Comment by 0xk1f0** [comment]
Please check [`v0.2.1`](https://github.com/0xk1f0/rwpspread/releases/tag/v0.2.1).

**Comment by apprehensions** [comment]
Thanks for your work.
